steps:
- name: 'mrtrustor/hugo:0.26'
  args: ['--buildDrafts', '--baseURL=https://blog-drafts.mrtrustor.net/']
  dir: 'blog'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-d', '-r', '-a', 'public-read', 'blog/public/', 'gs://blog-drafts.mrtrustor.net/']
