steps:
- id: 'Download academic theme'
  name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init', '--recursive']
- id: 'Run Hugo'
  name: 'mrtrustor/hugo:0.46'
  dir: 'blog'
- id: 'Publish to Cloud Storage'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-d', '-r', '-a', 'public-read', '-x', 'robots.txt', 'blog/public/', 'gs://blog.mrtrustor.net/']
