baseurl = "https://blog.mrtrustor.net/"
title = "MrTrustor's shiny blog"
copyright = "&copy; 2016-2017 Théo Chamley"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-80301889-1"


[params]
  name = "Théo Chamley"
  role = "Cloud Architect & DevOps engineer"
  organization = "Freelance & Oxalide"
  avatar = "moi.jpg"
  email = "theo.ch+blog@mley.fr"
  pgp = """
```nohightlight
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: GPGTools - http://gpgtools.org

mQMuBEu8VcsRCAC/Z5PO5nqL87I0cpXUramD+Ipk6d0OfwHV1eUZeAwWIrJwGqk3
09xr6FGNj2hkXMIGexQg2q4qVpAef9yscczNTNeFyk/wVtVxc6I2VC1g5BlrHUP8
ExE4aIiI30NNyvrT464WOV20fJoVcxncNcn10TkeA4WDRP5dC/KC50FkStmQyT/Z
RTxbAtP0KXuSmbyfpPeict3yN/Pr75+FgLxDscMa8+jteZ9aTXbPdgVYI1u3qD5S
YJc9MkuxwHRXy6NmvAYewOyM9iedm/Gs/zn0tChw/fUqbVWzmNkr7KgJY1fXE2hC
TdCwD3J0LoXeNg3PX6rVM+lmi04Edfk6wz7XAQDkaxIOzNKas28efTQfiy8dK6vR
Lt+rH2z5ZOYVVRSzSQf+OvOyFn79olPbid50glmwePSW5gT/2yXq56zbAxVNYRxt
7OcyO8D6VVU4/CG1kAdfl/jh2PM2kNMdpvDw7w6N+NddDvvAg5uouOBFNDQLzNq0
C9eIeFC3veAwUCJs6RQ79nexFDzuawGEYoZA/4xIZI5uyeh4xMljkfuWVFFsH8Mj
6tKZU05KS/n/QEN3L85bb7FVcH2hoT68V7ffSoTK2wGS3vraPI9tRa8X27hqO9YU
uYsZX92IC6YE8VMl/evhMU+QrrOHW3UXkT75TPNQUBU0QwLikEek69olUYOHyqB5
5iJ1d3ys22lcZq8dWjAFYbv4xzZTqj3/HsoYI+kQUQf/fFSJjO5KfuRSvOK+MZuI
I5jfZtscmH/iT/SbU6668bjX5ignSd8GXpPEys8O3AlqqLGpyjSgvSGaKCv9FoXG
HKHDvGAB5onyvngeN6bDPtJp1/CURx4okwg76+8rwaRLfYaq4ZVfP8tPhaYCgSWQ
iQnfIr/386MQjU/Pg2zEsekjxgN5cm4KylNLYSUHwPqq9QJ37EBvHP1TkFkWNt+A
zZu5+aWWhjc3Ep+B87tG/14nFdvwvke1wPG1HrHLC87PUTC3g8byC8LJtxk76Sxk
YACqWJ5dlhYo8kQN0Xft4c4cSbkD2Jli6M92f2tQNgn1ULl1Y5oqfbvU7yHCCvYt
Y7QfVGjDqW8gQ2hhbWxleSA8dGhlby5jaEBtbGV5LmZyPoiDBBMRCAArAhsDBQkM
UfAfBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAUCUgao5wIZAQAKCRAjX3ZrAyFS
X1UvAP9fjf603SiJLivixZ3wxGfFjAJo8xX9dIlFBZ0MlPGvuwEAruCpK7pL1QTZ
uNyyYkDASLQaqQpuBJ52GSSnoFzbgxy0JlRow6lvIENoYW1sZXkgPHRoZW8uY2hh
bWxleUBnbWFpbC5jb20+iIAEExEIACgCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4B
AheABQkMUfAfBQJSBqjnAAoJECNfdmsDIVJfez4A/2VpVAv4rAl3d3GqJ85UgtWL
pFaJscHT6vbQEvug0RxSAP9k+sB26LAhOUUruFKOPdJZ6KNiU4ZqYjrlGsRCxwFZ
OLQsVGjDqW8gQ2hhbWxleSAoS1RIIGFkZHJlc3MpIDxjaGFtbGV5QGt0aC5zZT6I
gAQTEQgAKAIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AFAlCJd/EFCQxR8B8A
CgkQI192awMhUl+wpgD/WUOnyNEpv+cU/PkAD+HEkpqQbBFgxXbsBZsGROwyZiQA
/3iI8FX2aCmYm0lbKRJbAKlgTQdGRSIdK6IsUsTVZeAMtC1UaMOpbyBDaGFtbGV5
IChvbGQgYWRkcmVzcykgPHRydXN0b3JAZnJlZS5mcj6IgAQTEQgAKAIbAwYLCQgH
AwIGFQgCCQoLBBYCAwECHgECF4AFAlCJd/EFCQxR8B8ACgkQI192awMhUl9QAAEA
soCVcvp7cQrr4//m7Z1n0E21cfdwJEmTwMHj/RbGOGEA/3QhONuSZp0j5OuV7oV5
DpS4KndlHyICVpJrNvBOmQYTtD1UaMOpbyBDaGFtbGV5IChFQ0wgYWRkcmVzcykg
PHRoZW8uY2hhbWxleUBlY2wyMDEyLmVjLWx5b24uZnI+iIAEExEIACgCGwMGCwkI
BwMCBhUIAgkKCwQWAgMBAh4BAheABQJQiXfxBQkMUfAfAAoJECNfdmsDIVJfqnAA
/jbPKwQDiCJ/xiLtFuQKTlblNsgJWBsT5lGwIrI2of2PAP9AjLMEAueF1Bs7KaHT
KCk7L96ktp2209OBkYPd5b+Rd7QoVGjDqW8gQ2hhbWxleSA8dGhlby5jaGFtbGV5
QG94YWxpZGUuY29tPoiBBBMRCAApBQJXjM9UAhsDBQkMUfAfBwsJCAcDAgEGFQgC
CQoLBBYCAwECHgECF4AACgkQI192awMhUl/0gwD/YYyl026/YxKLmXs0OW8OiymO
GdGLGm/sqnLsAoLcikEA/18N+naFMuGmbhzu0y7VK/+OeJ7s6jXLHL6TAtKceF+z
uQINBEu8VcsQCACsXWi/KQIoFGgurPT5ki8ir59fVfh3GMdib+B3+L/FJLnitiNS
4Gj6axlp1HTUb7Ux0kwc8i4y8RnRb8QsIG/dmVbAw9aR7RrLCFJE1r2kgBgaJBRa
SQtb+JnigM0Ip21gygtfSLceryBp9MGtbC0CSQEIx0F4zfogiafz4xAMh4LAKCK2
zYzAkbmNd90G+d3usf9KqT9dXCAlcub/P1t4bUwnxNq4czvlukr2bsyCDIctRqs6
x1+Cz9uPsFjlNvbqMqWkCWdD/APFktR58r2PKbAfiZ+6qPI/ZFhC2adtkCz2X0p+
9HYiU3SnYxdprP5vMObfQazNMak8irBe7GifAAMFCACFCdaANYIrCG/KmlDwEfQh
YRv+b7WQW3Ylp3oJ4+E8WDVLFfHeW3ebvr58+W4T6e9aR2aRlpRPzAGmBK2xUA2z
sRfO7IZr21yYd2CDV7pI0th/bSoYV6z6nRw4z5R0iicP8InanPrR25+h9SBrkEFX
Qjex8uOECqwAt33xIJP05EoyeX+XGD5AsA2PkooS2cjM1AhSz3b3AThTcA2r+41D
RqVr1mwd7oxFsx6F2VYIwkUJ6UnW6LU755wEmVZbp9wefguX2BSA3LqRlyP6Qeez
Iw/iTIWblDSRIavRSes1RcDyKmoluYipLk/AnGdsdSOy4miHDTtahD+74XV31aPV
iGcEGBEIAA8CGwwFAlCJeBAFCQxR8EUACgkQI192awMhUl+FQAEAqdJOVxHxsQE9
3TZBt7nJF5azLitAjnYXTbG5vKTOB40A/iST4+rk+lXPGCku9roRHLBnuKeZNQXA
xiq0GYIOGiR+
=3H5w
-----END PGP PUBLIC KEY BLOCK-----
```
"""
  #address = "Stanford AI Lab, Stanford University, California, 90210, USA."
  #phone = "888 888 88 88"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = ["Automation", "Software & infra architecture", "Artificial Intelligence"]
    str_interests = "Interests"
    str_education = "Diplomas"

    [[params.about.education]]
      course = "LFS258 - Kubernetes Fundamentals"
      institution = "The Linux Foundation"
      year = 2017

    [[params.about.education]]
      course = "Machine Learning"
      institution = "Standford - Coursera MOOC, TDEMGCBZU5U8"
      year = 2016

    [[params.about.education]]
      course = "Certified Cloud Architect"
      institution = "Google, Cert. ID: 3jgAQY"
      year = 2017

    [[params.about.education]]
      course = "Solutions Architect – Professional"
      institution = "Amazon Web Services, AWS-PSA-1551"
      year = 2015

    [[params.about.education]]
      course = "Civilingenjör (M Sc./Eng.)"
      institution = "Kungliga Tekniska Högskolan (Stockholm, Sweden)"
      year = 2012

    [[params.about.education]]
      course = "Ingénieur (M Sc./Eng.)"
      institution = "Ecole Centrale de Lyon (Lyon, France)"
      year = 2011

  # Selected Publications section.
  # Section will only be displayed if there are publications with `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  #[params.projects]
  #  title = "Projects"
  #  subtitle = ""

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:theo.ch+blog@mley.fr"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/MrTrustor"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/MrTrustor"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/theo-chamley"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

#[[menu.main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 3
