baseurl = "http://blog.mrtrustor.net/"
title = "MrTrustor's shiny blog"
copyright = "&copy; 2016 Théo Chamley"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
  name = "Théo Chamley"
  role = "Cloud Architect & DevOps engineer"
  organization = "Freelance & Oxalide"
  avatar = "moi.jpg"
  email = "theo.ch+blog@mley.fr"
  #address = "Stanford AI Lab, Stanford University, California, 90210, USA."
  #phone = "888 888 88 88"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = ["Automation", "Software & infra architecture", "Artificial Intelligence"]
    str_interests = "Interests"
    str_education = "Diplomas"

    [[params.about.education]]
      course = "Solutions Architect – Professional"
      institution = "Amazon Web Services, AWS-PSA-1551"
      year = 2015

    [[params.about.education]]
      course = "Civilingenjör (M Sc./Eng.)"
      institution = "Kungliga Tekniska Högskolan (Stockholm, Sweden)"
      year = 2012

    [[params.about.education]]
      course = "Ingénieur (M Sc./Eng.)"
      institution = "Ecole Centrale de Lyon (Lyon, France)"
      year = 2011

  # Selected Publications section.
  # Section will only be displayed if there are publications with `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:theo.ch+blog@mley.fr"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/MrTrustor"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/MrTrustor"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/theo-chamley"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4
